language: node_js
node:
  -"10.7.0"

script:
  -npm install
  -npm test

after_script:
  -npm run coverage
  # - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

# env:
#  global:
#    - export NODE_ENV=test